create table teacher (
  id       varchar(24) not null,
  password varchar(64) not null,
  name     varchar(36) not null,

  primary key (id)
);

create table student (
  id         varchar(24) not null,
  password   varchar(64) not null,
  name       varchar(36) not null,
  class_name varchar(36) not null,
  major_name varchar(72) not null,

  primary key (id)
);

create table course (
  id      bigint      not null generated by default as identity,
  name    varchar(24) not null,
  teacher varchar(24) not null,

  primary key (id),
  unique (teacher, name),
  foreign key (teacher) references teacher (id)
);

create table course_student (
  student varchar(24) not null,
  course  bigint      not null,
  score   decimal(5, 2),

  primary key (student, course),
  foreign key (student) references student (id),
  foreign key (course) references course (id)
);
